= 
:allow-uri-read: 


[role="tabbed-block"]
====
.AWS / VMC
--
In diesem Abschnitt wird beschrieben, wie Sie VMware Cloud on AWS SDDC einrichten und verwalten und es in Kombination mit den verfügbaren Optionen zum Verbinden von NetApp -Speicher verwenden.


NOTE: In-Guest-Speicher ist die einzige unterstützte Methode zum Verbinden von Cloud Volumes ONTAP mit AWS VMC.

Der Einrichtungsprozess kann in die folgenden Schritte unterteilt werden:

* Bereitstellen und Konfigurieren von VMware Cloud für AWS
* Verbinden Sie VMware Cloud mit FSx ONTAP


Sehen Sie sich die detailliertelink:../vmware/vmw-aws-vmc-setup.html["Konfigurationsschritte für VMC"] .

Sehen Sie sich die detailliertelink:../vmware/vmw-aws-vmc-setup.html["Konfigurationsschritte für VMC"] .

--
.Azure / AVS
--
In diesem Abschnitt wird beschrieben, wie Sie Azure VMware Solution einrichten und verwalten und in Kombination mit den verfügbaren Optionen zum Anbinden von NetApp -Speicher verwenden.


NOTE: In-Guest-Speicher ist die einzige unterstützte Methode zum Verbinden von Cloud Volumes ONTAP mit Azure VMware Solution.

Der Einrichtungsprozess kann in die folgenden Schritte unterteilt werden:

* Registrieren des Ressourcenanbieters und Erstellen einer privaten Cloud
* Herstellen einer Verbindung mit einem neuen oder vorhandenen virtuellen ExpressRoute-Netzwerkgateway
* Überprüfen Sie die Netzwerkkonnektivität und greifen Sie auf die private Cloud zu


Sehen Sie sich die detailliertelink:../vmware/vmw-azure-avs-setup.html["Konfigurationsschritte für AVS"] .

Sehen Sie sich die detailliertelink:../vmware/vmw-azure-avs-setup.html["Konfigurationsschritte für AVS"] .

--
.GCP / GCVE
--
In diesem Abschnitt wird beschrieben, wie Sie GCVE einrichten und verwalten und es in Kombination mit den verfügbaren Optionen zum Anschließen von NetApp -Speicher verwenden.


NOTE: In-Guest-Speicher ist die einzige unterstützte Methode zum Verbinden von Cloud Volumes ONTAP und Google Cloud NetApp Volumes mit GCVE.

Der Einrichtungsprozess kann in die folgenden Schritte unterteilt werden:

* Bereitstellen und Konfigurieren von GCVE
* Privaten Zugriff auf GCVE aktivieren


Sehen Sie sich die detailliertelink:../vmware/vmw-gcp-gcve-setup.html["Konfigurationsschritte für GCVE"] .

Sehen Sie sich die detailliertelink:../vmware/vmw-gcp-gcve-setup.html["Konfigurationsschritte für GCVE"] .

--
====