---
sidebar: sidebar 
permalink: vmware/vmw-azure-avs-overview.html 
keywords: NetApp Solutions, hyperscalers, azure, avs, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= NetApp -Funktionen für Azure AVS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Erfahren Sie mehr über die Funktionen, die NetApp in die Azure VMware Solution (AVS) einbringt – von NetApp als über einen Gast verbundenes Speichergerät oder als zusätzlicher NFS-Datenspeicher bis hin zur Migration von Workflows, Erweiterung/Bursting in die Cloud, Sicherung/Wiederherstellung und Notfallwiederherstellung.

Springen Sie zum Abschnitt mit dem gewünschten Inhalt, indem Sie eine der folgenden Optionen auswählen:

* link:#config["Konfigurieren von AVS in Azure"]
* link:#datastore["NetApp Storage-Optionen für AVS"]
* link:#solutions["NetApp / VMware Cloud-Lösungen"]




== Konfigurieren von AVS in Azure

Wie bei der lokalen Umgebung ist die Planung einer Cloud-basierten Virtualisierungsumgebung entscheidend für eine erfolgreiche produktionsbereite Umgebung zum Erstellen und Migrieren von VMs.

In diesem Abschnitt wird beschrieben, wie Sie Azure VMware Solution einrichten und verwalten und in Kombination mit den verfügbaren Optionen zum Anbinden von NetApp -Speicher verwenden.


NOTE: In-Guest-Speicher ist die einzige unterstützte Methode zum Verbinden von Cloud Volumes ONTAP mit Azure VMware Solution.

Der Einrichtungsprozess kann in die folgenden Schritte unterteilt werden:

* Registrieren des Ressourcenanbieters und Erstellen einer privaten Cloud
* Herstellen einer Verbindung mit einem neuen oder vorhandenen virtuellen ExpressRoute-Netzwerkgateway
* Überprüfen Sie die Netzwerkkonnektivität und greifen Sie auf die private Cloud zu


Sehen Sie sich die detailliertelink:azure-setup.html["Konfigurationsschritte für AVS"] .



== NetApp Storage-Optionen für AVS

NetApp Speicher kann innerhalb von Azure AVS auf verschiedene Weise genutzt werden – entweder als verbundener Speicher oder als zusätzlicher NFS-Datenspeicher.

Bitte besuchen Sielink:vmw-hybrid-support-configs.html["Unterstützte NetApp -Speicheroptionen"] für weitere Informationen.

Azure unterstützt NetApp -Speicher in den folgenden Konfigurationen:

* Azure NetApp Files (ANF) als mit dem Gast verbundener Speicher
* Cloud Volumes ONTAP (CVO) als mit dem Gast verbundener Speicher
* Azure NetApp Files (ANF) als ergänzender NFS-Datenspeicher


Sehen Sie sich die detailliertelink:azure-guest.html["Gastverbindungs-Speicheroptionen für AVS"] .  Sehen Sie sich die detailliertelink:azure-native-nfs-datastore-option.html["zusätzliche NFS-Datenspeicheroptionen für AVS"] .



== Anwendungsfälle der Lösung

Mit NetApp und VMware-Cloudlösungen lassen sich viele Anwendungsfälle einfach in Azure AVS bereitstellen. Diese Fälle sind für jeden der von VMware definierten Cloudbereiche definiert:

* Schützen (beinhaltet sowohl Disaster Recovery als auch Backup/Wiederherstellung)
* Verlängern
* Wandern


link:vmw-azure-avs-solutions.html["Durchsuchen Sie die NetApp -Lösungen für Azure AVS"]
