---
sidebar: sidebar 
permalink: google/gcp-gcnv-firewall.html 
keywords: tcp, nfs, smb share, kerberos, active directory, dns 
summary: Google Cloud NetApp Volumes stellt mehrere TCP-Ports bereit, um NFS- und SMB-Freigaben bereitzustellen. 
---
= Firewall
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Google Cloud NetApp Volumes stellt mehrere TCP-Ports bereit, um NFS- und SMB-Freigaben bereitzustellen:

* https://cloud.google.com/architecture/partners/netapp-cloud-volumes/security-considerations?hl=en_US["Für den NFS-Zugriff erforderliche Ports"^]
* https://cloud.google.com/architecture/partners/netapp-cloud-volumes/security-considerations?hl=en_US["Für den SMB-Zugriff erforderliche Ports"^]


Darüber hinaus erfordern SMB, NFS mit LDAP einschließlich Kerberos und Dualprotokollkonfigurationen Zugriff auf eine Windows Active Directory-Domäne.  Active Directory-Verbindungen müssen https://cloud.google.com/architecture/partners/netapp-cloud-volumes/creating-smb-volumes?hl=en_US["konfiguriert"^] auf regionaler Basis.  Active Directory Domänencontroller (DC) werden identifiziert durch https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/7fcdce70-5205-44d6-9c3a-260e616a2f04["DNS-basierte DC-Erkennung"^] unter Verwendung der angegebenen DNS-Server.  Alle zurückgegebenen DCs werden verwendet.  Die Liste der berechtigten DCs kann durch Angabe eines Active Directory-Standorts eingeschränkt werden.

Google Cloud NetApp Volumes erreicht mit IP-Adressen aus dem CIDR-Bereich, der mit dem `gcloud compute address` Befehl während https://cloud.google.com/architecture/partners/netapp-cloud-volumes/setting-up-private-services-access?hl=en_US["Onboarding der Google Cloud NetApp Volumes"^] .  Sie können dieses CIDR als Quelladressen verwenden, um eingehende Firewalls für Ihre Active Directory-Domänencontroller zu konfigurieren.

Active Directory-Domänencontroller müssen https://cloud.google.com/architecture/partners/netapp-cloud-volumes/security-considerations?hl=en_US["Ports für die Google Cloud NetApp Volumes CIDRs verfügbar machen, wie hier erwähnt"^] .
