---
sidebar: sidebar 
permalink: google/gcp-gcnv-service-operation.html 
keywords: physical security, operations team, customer responsibilities, malicious sre protection, certifications, gdpr 
summary: Das Google Cloud NetApp Volumes -Team verwaltet die Backend-Dienste in Google Cloud und verwendet mehrere Strategien, um die Plattform zu sichern und unerwünschten Zugriff zu verhindern. 
---
= Servicebetrieb
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Das Google Cloud NetApp Volumes -Team verwaltet die Backend-Dienste in Google Cloud und verwendet mehrere Strategien, um die Plattform zu sichern und unerwünschten Zugriff zu verhindern.

Jeder Kunde erhält sein eigenes, einzigartiges Subnetz, dessen Zugriff standardmäßig von anderen Kunden abgeschottet ist, und jeder Mandant in Google Cloud NetApp Volumes erhält seinen eigenen Namespace und sein eigenes VLAN zur vollständigen Datenisolierung.  Nachdem ein Benutzer authentifiziert wurde, kann die Service Delivery Engine (SDE) nur die für diesen Mandanten spezifischen Konfigurationsdaten lesen.



== Physische Sicherheit

Mit der entsprechenden Vorabgenehmigung haben nur Techniker vor Ort und Field Support Engineers (FSEs) mit NetApp Ausweis Zugriff auf den Käfig und die Racks für physische Arbeiten.  Speicher- und Netzwerkverwaltung ist nicht zulässig.  Nur diese Ressourcen vor Ort können Hardware-Wartungsaufgaben durchführen.

Für Techniker vor Ort wird ein Ticket für die Leistungsbeschreibung (SOW) erstellt, das die Rack-ID und den Gerätestandort (RU) sowie alle anderen Details enthält.  Für NetApp FSEs muss beim COLO ein Site-Besuchsticket erstellt werden, das zu Prüfzwecken die Details, das Datum und die Uhrzeit des Besuchers enthält.  Die Leistungsbeschreibung für den FSE wird NetApp intern mitgeteilt.



== Betriebsteam

Das Betriebsteam für Google Cloud NetApp Volumes besteht aus einem Produktionsingenieur und einem Site Reliability Engineer (SRE) für Google Cloud NetApp Volumes sowie NetApp Field Support Engineers und Partnern für die Hardware.  Alle Mitglieder des Betriebsteams sind für die Arbeit in Google Cloud akkreditiert und für jedes erstellte Ticket werden detaillierte Arbeitsaufzeichnungen geführt.  Darüber hinaus gibt es einen strengen Änderungskontroll- und Genehmigungsprozess, um sicherzustellen, dass jede Entscheidung angemessen geprüft wird.

Das SRE-Team verwaltet die Steuerebene und die Art und Weise, wie die Daten von UI-Anfragen an die Backend-Hardware und -Software in Google Cloud NetApp Volumes weitergeleitet werden.  Das SRE-Team verwaltet auch Systemressourcen wie Volume- und Inode-Maxima.  SREs dürfen nicht mit Kundendaten interagieren oder auf diese zugreifen.  SREs übernehmen außerdem die Koordination von RMAs (Return Material Authorizations), beispielsweise bei Anfragen zum Austausch neuer Festplatten oder Arbeitsspeicher für die Backend-Hardware.



== Kundenpflichten

Kunden von Google Cloud NetApp Volumes verwalten das Active Directory und die Benutzerrollenverwaltung ihres Unternehmens sowie die Volume- und Datenvorgänge.  Kunden können über Administratorrollen verfügen und Berechtigungen an andere Endbenutzer innerhalb desselben Google Cloud-Projekts delegieren, indem sie die beiden vordefinierten Rollen verwenden, die NetApp und Google Cloud bereitstellen (Administrator und Viewer).

Der Administrator kann jedes VPC innerhalb des Kundenprojekts mit Google Cloud NetApp Volumes verbinden, das der Kunde für geeignet hält.  Es liegt in der Verantwortung des Kunden, den Zugriff auf sein Google Cloud Marketplace-Abonnement zu verwalten und die VPCs zu verwalten, die Zugriff auf die Datenebene haben.



== Schutz vor bösartigen SREs

Eine mögliche Frage ist, wie Google Cloud NetApp Volumes vor Szenarien schützt, in denen ein bösartiger SRE vorhanden ist oder SRE-Anmeldeinformationen kompromittiert wurden.

Der Zugriff auf die Produktionsumgebung ist nur einer begrenzten Anzahl von SRE-Mitarbeitern gestattet.  Darüber hinaus sind die Administratorrechte auf eine Handvoll erfahrener Administratoren beschränkt.  Alle von Personen in der Google Cloud NetApp Volumes -Produktionsumgebung ausgeführten Aktionen werden protokolliert und alle Anomalien der Basislinie oder verdächtigen Aktivitäten werden von unserer Threat Intelligence-Plattform für Security Information and Event Management (SIEM) erkannt.  Dadurch können böswillige Aktionen verfolgt und abgemildert werden, bevor dem Backend von Google Cloud NetApp Volumes zu großer Schaden zugefügt wird.



== Volume-Lebenszyklus

Google Cloud NetApp Volumes verwaltet nur die Objekte innerhalb des Dienstes, nicht die Daten innerhalb der Volumes.  Nur Clients, die auf die Volumes zugreifen, können die Daten, die ACLs, Dateieigentümer usw. verwalten.  Die Daten in diesen Volumes werden im Ruhezustand verschlüsselt und der Zugriff ist auf Mandanten der Google Cloud NetApp Volumes Instanz beschränkt.

Der Volume-Lebenszyklus für Google Cloud NetApp Volumes ist Erstellen-Aktualisieren-Löschen.  Volumes behalten Snapshot-Kopien von Volumes bei, bis die Volumes gelöscht werden, und nur validierte Google Cloud NetApp Volumes Administratoren können Volumes in Google Cloud NetApp Volumes löschen.  Wenn ein Administrator die Löschung eines Volumes anfordert, ist zur Bestätigung der Löschung ein zusätzlicher Schritt zur Eingabe des Volumenamens erforderlich.  Nachdem ein Volume gelöscht wurde, ist es verloren und kann nicht wiederhergestellt werden.

In Fällen, in denen ein Google Cloud NetApp Volumes -Vertrag gekündigt wird, markiert NetApp Volumes nach einem bestimmten Zeitraum zum Löschen.  Vor Ablauf dieser Frist können Sie auf Kundenwunsch Volumes wiederherstellen.



== Zertifizierungen

Google Cloud NetApp Volumes für Google Cloud ist derzeit nach den Standards ISO/IEC 27001:2013 und ISO/IEC 27018:2019 zertifiziert.  Der Dienst hat außerdem vor Kurzem seinen SOC2 Typ I-Bescheinigungsbericht erhalten.  Informationen zum Engagement von NetApp für Datensicherheit und Datenschutz finden Sie unter https://www.netapp.com/company/trust-center/compliance/["Compliance: Datensicherheit und Datenschutz"^] .



== DSGVO

Unsere Verpflichtungen zum Datenschutz und zur Einhaltung der DSGVO sind in einer Reihe unserer https://www.netapp.com/how-to-buy/sales-terms-and-conditions%22%20/o%20%22SEO%20-%20Sales%20Terms%20and%20Conditions["Kundenverträge"^] , wie zum Beispiel unsere https://netapp.na1.echosign.com/public/esignWidget?wid=CBFCIBAA3AAABLblqZhCqPPgcufskl_71q-FelD4DHz5EMJVOkqqT0iiORT10DlfZnZeMpDrse5W6K9LEw6o*["Nachtrag zur Data Processing"^] , die die https://ec.europa.eu/info/law/law-topic/data-protection/international-dimension-data-protection/standard-contractual-clauses-scc_en["Standardvertragsklauseln"^] bereitgestellt von der Europäischen Kommission.  Diese Verpflichtungen gehen wir auch in unserer Datenschutzrichtlinie ein, die durch die in unserem Unternehmensverhaltenskodex festgelegten Grundwerte gestützt wird.
