---
sidebar: sidebar 
permalink: google/gcp-gcnv-data-encrypt-at-rest.html 
keywords: aes-256 encryption, cmek 
summary: Alle Volumes in Google Cloud NetApp Volumes werden im Ruhezustand mit AES-256-Verschlüsselung verschlüsselt. Dies bedeutet, dass alle auf Medien geschriebenen Benutzerdaten verschlüsselt sind und nur mit einem Schlüssel pro Volume entschlüsselt werden können. 
---
= Datenverschlüsselung im Ruhezustand
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Alle Volumes in Google Cloud NetApp Volumes werden im Ruhezustand mit AES-256-Verschlüsselung verschlüsselt. Dies bedeutet, dass alle auf Medien geschriebenen Benutzerdaten verschlüsselt sind und nur mit einem Schlüssel pro Volume entschlüsselt werden können.

* Für NetApp Volumes-SW werden von Google generierte Schlüssel verwendet.
* Für NetApp Volumes-Performance werden die Schlüssel pro Volume in einem in die Google Cloud NetApp Volumes integrierten Schlüsselmanager gespeichert.


Ab November 2021 wurde die Vorschaufunktion für kundenverwaltete Verschlüsselungsschlüssel (CMEK) verfügbar gemacht.  Dadurch können Sie die Schlüssel pro Volume mit einem pro Projekt und pro Region gültigen Hauptschlüssel verschlüsseln, der in https://cloud.google.com/kms/docs["Google Schlüsselverwaltungsdienst (KMS)."^] KMS ermöglicht Ihnen das Anschließen externer Schlüsselmanager.

Informationen zum Konfigurieren von KMS für NetApp Volumes-Performance finden Sie unter https://cloud.google.com/architecture/partners/netapp-cloud-volumes/customer-managed-keys?hl=en_US["Einrichten von kundenverwalteten Verschlüsselungsschlüsseln"^] .
