---
sidebar: sidebar 
permalink: videos/hmc-aws-videos.html 
summary: Videos und Demos präsentieren AWS Hybrid Multicloud-Lösungen mit NetApp 
keywords: hybrid cloud, rosa, fsx ontap, azure vmware, netapp hci, videos, demos 
---
= Sehen Sie sich Videos zu Hybrid-Multicloud-Lösungen für Amazon Web Services mit NetApp an
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Entdecken Sie die umfassende Videobibliothek von NetApp mit hybriden Multicloud-Lösungen für AWS mit NetApp.  Sehen Sie sich Videos zu Gastspeicher, TCO-Einsparungen, zusätzlichen Datenspeichern und Migrations-Workflows für VMware Cloud auf AWS und Amazon FSx für ONTAP an, einschließlich Windows- und Linux-Szenarien.



== Mit dem Gast verbundener Speicher

.Windows Guest Connected Storage mit FSx ONTAP unter Verwendung von iSCSI
video::0d03e040-634f-4086-8cb5-b01200fb8515[panopto,width=360]
.Linux Guest Connected Storage mit FSx ONTAP unter Verwendung von NFS
video::c3befe1b-4f32-4839-a031-b01200fb6d60[panopto,width=360]


== Gesamtbetriebskosten und zusätzliche Datenspeicher

.VMware Cloud auf AWS TCO-Einsparungen mit Amazon FSx ONTAP
video::f0fedec5-dc17-47af-8821-b01200f00e08[panopto,width=360]
.VMware Cloud auf AWS-Zusatzdatenspeicher mit Amazon FSx ONTAP
video::2065dcc1-f31a-4e71-a7d5-b01200f01171[panopto,width=360]


== Migrations-Workflows (HCX)

.VMware HCX-Bereitstellung und Konfigurations-Setup für VMC
video::6132c921-a44c-4c81-aab7-b01200fb5d29[panopto,width=360]
.vMotion-Migrationsdemonstration mit VMware HCX für VMC und FSx ONTAP
video::52661f10-3f90-4f3d-865a-b01200f06d31[panopto,width=360]
.Demonstration der Kaltmigration mit VMware HCX für VMC und FSx ONTAP
video::685c0dc2-9d8a-42ff-b46d-b01200f056b0[panopto,width=360]